server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/gp?serverTimezone=GMT
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.wyf.examples.model
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    root: info
#    com.wyf.examples.dao: debug
#    org.mybatis: debug
